print("GOOD AFTERNOON LORA!")
response = input("Are you excited for the day?")
print("I am glad to hear that")
response2 = input("How is your cat doing?")
print("Make sure to cuddle her for me")
response3 = input("Nikuambie kitu?")
print("Unakaa smart <3 <3 <3")
response4 = input("Nikuambie kitu ingine, na si kwa ubaya?")
print("The edges are not edging")
response5 = input("Lakini?")
print("Kwani huna gel")
response6 = input("Gai, sasa umejam!")
print("Pole basi, tuende kazi bae ;)")

num_1 = int(input("Enter a number"))
num_2 = int(input("Enter a second number"))
result = num_2 + num_1
print(num_1)
print(num_2)
print(result)
